name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: bs-gen
        path: dist-newstyle/build/x86_64-linux/ghc-8.10.3/bs-gen-0.1.2.0/x/bs_gen/build/bs_gen/bs_gen

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: bs-gen
    - name: ls
      run: ls -ltr ..
    - name: pwd
      run: pwd
    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ../Dockerfile
        push: false
        tags: asdf/qwer:1.2.3
